version: '3.4'

x-app: &app-common
  build:
    context: .
    dockerfile: .docker/services/php/Dockerfile
    target: development
    args:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
  volumes:
    - .:/var/www/html

services:
  web-server:
    build:
      context: .
      dockerfile: ./.docker/services/nginx/Dockerfile
      target: runtime
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./public/index.php:/usr/share/nginx/html/index.php
      - ./.docker/services/nginx/config/default.conf:/etc/nginx/conf.d/default.conf

  app:
    <<: *app-common
    environment:
      CONTAINER_ROLE: "app"
    env_file:
      - .env
    depends_on:
      - mysql

  scheduler:
    <<: *app-common
    environment:
      CONTAINER_ROLE: "scheduler"
    env_file:
      - .env
    depends_on:
      - mysql


  mysql:
    image: mysql:8.0
    command:
      --default-authentication-plugin=mysql_native_password
      --performance-schema=OFF
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}


volumes:
  mysql:
    driver: "local"
